Repository brendenwest/cascade, pull requests merged in 2021-11, with the labels that each got.

#30 Screen navigation
  App.js
  android/app/src/main/java/com/cascadebikeclub/MainActivity.java
  components/routes/Drawers.js
  components/routes/Tabs.js
  components/screens/AboutScreen/AboutScreen.js
  components/screens/BlogScreen/BlogScreen.js
  components/screens/CalendarScreen/CalendarScreen.js
  components/screens/HomeScreen/HomeScreen.js
  components/screens/HomeScreen/HomeStyleSheet.js
  index.js
  package-lock.json
  package.json
Labels: task, new feature

#32 Minor spelling errors
  README.md
Labels: documentation

#31 add daily rides screen with drawer navigation
  components/routes/Drawers.js
  components/screens/DailyRidesScreen/DailyRidesScreen.js
  components/screens/DailyRidesScreen/DailyRidesStyles.js
Labels: task

#33 Bundler Rename
  android/app/_BUCK
  android/app/build.gradle
  android/app/src/debug/java/org/cascade/ReactNativeFlipper.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/org/cascade/MainActivity.java
  android/app/src/main/java/org/cascade/MainApplication.java
  android/app/src/main/res/values/strings.xml
  android/settings.gradle
  app.json
  package.json
Labels: task

#44 In-app links for button leading to Cascade's website
  android/build.gradle
  components/screens/AboutScreen/SocialMedia/SocialMedia.js
  package-lock.json
  package.json
Labels: task

#39 Daily Rides API and Site Linking
  components/routes/Stack.js
  components/screens/DailyRidesScreen/DailyRidesScreen.js
  components/screens/DailyRidesScreen/DailyRidesStyles.js
Labels: task

#43 Blog screen implementation
  .eslintrc.js
  components/screens/BlogScreen/BlogScreen.js
  components/screens/BlogScreen/BlogStyles.js
  package-lock.json
Labels: task

#51 Updated based on https://github.com/brendenwest/cascade/issues/28
  README.md
Labels: documentation

#53 Blog screen developement
  components/screens/BlogScreen/BlogScreen.js
  components/screens/BlogScreen/BlogStyles.js
Labels: task

#42 Calendar Screen
  components/screens/CalendarScreen/CalendarScreen.js
  components/screens/CalendarScreen/CalendarStyles.js
Labels: task

#50 Contact Us screen
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/org/cascade/MainApplication.java
  components/routes/Drawers.js
  components/screens/ContactScreen/ContactScreen.js
  components/screens/ContactScreen/ContactStyles.js
  package-lock.json
  package.json
Labels: task
